[project]
name = "SQL_Engine"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
dev-dependencies = [
    "pytest>=8.2.2",
    "ruff>=0.7.0",
    "pyinstaller",
]
